### ISSUE TITLE
IMDB name converter raising internal exception

### ISSUE THREAD

**Issue by pappes** [pappes/MyMovieSearch#26]
nm4240546
 type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type '<dynamic>'.
on my_movie_search/movies/web_data_providers/detail/converters/imdb_name.dart:41:31) in functiono _dtoFromMap(Map map)
code =   for (final category in map[outerElementRelated]) {

Action: reproduce in a unit test

flutter: [38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: [38;5;196m│ #0   WebFetchBase.baseTransformMapToOutputHandler (package:my_movie_search/utilities/web_data/web_fetch_base.dart:305:16)
flutter: [38;5;196m│ #1   ScrapeIMDBNameDetails.myTransformTextStreamToOutputObject (package:my_movie_search/movies/web_data_providers/detail/webscrapers/imdb_name.dart:28:32)
flutter: [38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: [38;5;196m│ ⛔ Exception raised during myTransformMapToOutput for _getFetchContext, constructing error for data {@context: http://schema.org, @type: Person, url: /name/nm4240546/, name: Artur, jobTitle: [Actor, Writer, Producer], description: Artur is an actor and writer, known for Mafia (2014), CSI: NY (2004) and Monster (2014)., 
related: {actor: [{name: Mafia, url: /title/tt3901190/?ref_=nm_flmg_act_1}, {name: Finding Johnny, url: /title/tt6918772/?ref_=nm_flmg_act_2}, {name: Shooter, url: /title/tt4181172/?ref_=nm_flmg_act_3}, {name: Seeing Through, url: /title/tt3293870/?ref_=nm_flmg_act_4}, {name: Night of the Wild, url: /title/tt4926042/?ref_=nm_flmg_act_5}, {name: Fairlady, url: /title/tt4203530/?ref_=nm_flmg_act_6}, {name: Keep It Together, url: /title/tt3488712/?ref_=nm_flmg_act_7}, {name: Monster, url: /title/tt3901202/?ref_=nm_flmg_act_8}, {name: Nightcrawler, url: /title/tt2872718/?ref_=nm_flmg_act_9}, {name: 21 & Over, url: /title/tt1711425/?ref_=nm_flmg_act_10}, {name: Behind the Scenes, url: /title/tt2109280/?ref_=nm_flmg_act_11}, {name: Community, url: /title/tt1439629/?ref_=nm_flmg_act_12}, {name: Pride, url: /title/tt2043966/?ref_=nm_flmg_act_13}, {name: CSI: NY, url: /title/tt0395843/?ref_=nm_flmg_act_14}], 
writer: [{name: Mafia, url: /title/tt3901190/?ref_=nm_flmg_wr_1}, {name: Finding Johnny, url: /title/tt6918772/?ref_=nm_flmg_wr_2}, {name: Monster, url: /title/tt3901202/?ref_=nm_flmg_wr_3}], 
producer: [{name: Mafia, url: /title/tt3901190/?ref_=nm_flmg_prd_1}, {name: Finding Johnny, url: /title/tt6918772/?ref_=nm_flmg_prd_2}, {name: Monster, url: /title/tt3901202/?ref_=nm_flmg_prd_3}], 
director: [{name: Mafia, url: /title/tt3901190/?ref_=nm_flmg_dr_1}, {name: Finding Johnny, url: /title/tt6918772/?ref_=nm_flmg_dr_2}, {name: Monster, url: /title/tt3901202/?ref_=nm_flmg_dr_3}]}
, id: nm4240546}
flutter: [38;5;196m│ ⛔  type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type '<dynamic>'.
flutter: [38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: [38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: [38;5;12m│ #0   WebFetchBase.baseTransformMapToOutputHandler (package:my_movie_search/utilities/web_data/web_fetch_base.dart:310:16)
flutter: [38;5;12m│ #1   ScrapeIMDBNameDetails.myTransformTextStreamToOutputObject (package:my_movie_search/movies/web_data_providers/detail/webscrapers/imdb_name.dart:28:32)
flutter: [38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: [38;5;12m│ 💡 QueryIMDBNameDetails .myTransformMapToOutput stacktrace: #0      ImdbNamePageConverter._dtoFromMap (package:my_movie_search/movies/web_data_providers/detail/converters/imdb_name.dart:41:31)
flutter: [38;5;12m│ 💡 #1      ImdbNamePageConverter.dtoFromCompleteJsonMap (package:my_movie_search/movies/web_data_providers/detail/converters/imdb_name.dart:22:13)
flutter: [38;5;12m│ 💡 #2      QueryIMDBNameDetails.myTransformMapToOutput (package:my_movie_search/movies/web_data_providers/detail/imdb_name.dart:48:29)
flutter: [38;5;12m│ 💡 #3      WebFetchBase.baseTransformMapToOutputHandler (package:my_movie_search/utilities/web_data/web_fetch_base.dart:298:22)
flutter: [38;5;12m│ 💡 #4      ScrapeIMDBNameDetails.myTransformTextStreamToOutputObject (package:my_movie_search/movies/web_data_providers/detail/webscrapers/imdb_name.dart:28:32)
flutter: [38;5;12m│ 💡 <asynchronous suspension>
flutter: [38;5;12m│ 💡 
flutter: [38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by pappes** [comment]
fixed
